const UNAUTHORIZED_STATUS = 401;
const FORBIDDEN_STATUS = 403;
const NOT_FOUND_STATUS = 404;
const INTERNAL_SERVER_ERROR_STATUS = 500;
const BAD_REQUEST_STATUS = 400;
const OK_STATUS = 200;

module.exports = {
    UNAUTHORIZED_STATUS,
    FORBIDDEN_STATUS,
    NOT_FOUND_STATUS,
    INTERNAL_SERVER_ERROR_STATUS,
    BAD_REQUEST_STATUS,
    OK_STATUS
}
